-- Anderson Adon aadon1, Eugene Asare easare3

DROP TABLE IF EXISTS Bill_Subject;
DROP TABLE IF EXISTS Cosponsor;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Sponsor;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS Bill;
DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Congress;
