-- Anderson Adon aadon1, Eugene Asare easare3

DROP TABLE IF EXISTS Bill_Subject;
DROP TABLE IF EXISTS Cosponsor;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Sponsor;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS Vote;
DROP TABLE IF EXISTS Bill;
DROP TABLE IF EXISTS Area;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Congress;

DROP PROCEDURE IF EXISTS AgeRange;
DROP PROCEDURE IF EXISTS AgeSexDistribution;
DROP PROCEDURE IF EXISTS BillCountByParty;
DROP PROCEDURE IF EXISTS Bills_By;
DROP PROCEDURE IF EXISTS Bills_By_Filter;
DROP PROCEDURE IF EXISTS Bills_By_State;
DROP PROCEDURE IF EXISTS Bipartisan_Votes;
DROP PROCEDURE IF EXISTS BirthdayDistribution;
DROP PROCEDURE IF EXISTS GetAreasInBills;
DROP PROCEDURE IF EXISTS GetMembersByBirthday;
DROP PROCEDURE IF EXISTS HouseSeatChanges;
DROP PROCEDURE IF EXISTS PartisanBills;
DROP PROCEDURE IF EXISTS PartyUnityForBill;
DROP PROCEDURE IF EXISTS TopBillsInSenate;

DROP PROCEDURE IF EXISTS InsertMember;
DROP PROCEDURE IF EXISTS InsertRole;
DROP PROCEDURE IF EXISTS InsertBill;
DROP PROCEDURE IF EXISTS InsertBillSubject;
DROP PROCEDURE IF EXISTS InsertSponsor;
DROP PROCEDURE IF EXISTS InsertCosponsor;
DROP PROCEDURE IF EXISTS InsertVote;

DROP PROCEDURE IF EXISTS DeleteMember;
DROP PROCEDURE IF EXISTS DeleteRole;
DROP PROCEDURE IF EXISTS DeleteBill;
DROP PROCEDURE IF EXISTS DeleteBillSubject;
DROP PROCEDURE IF EXISTS DeleteSponsor;
DROP PROCEDURE IF EXISTS DeleteCosponsor;
DROP PROCEDURE IF EXISTS DeleteVote;